name: Build LLVM for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Docker
      run: |
        docker pull termux/package-builder:latest
        
    - name: Build LLVM
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace termux/package-builder:latest bash -c '
          # 安装必要的构建工具
          apt update
          apt install -y cmake ninja-build python3 git

          cd /workspace
          
          # 1. Clone LLVM
          git clone --filter=blob:none --sparse https://github.com/llvm/llvm-project.git
          cd llvm-project
          
          # 2. Sparse checkout
          git sparse-checkout init --cone
          git sparse-checkout set clang llvm cmake
          
          # 3. Create build directory
          mkdir build
          cd build
          
          # 4. Configure CMake
          cmake ../llvm \
            -DLLVM_ENABLE_PROJECTS=clang \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            -DLLVM_ENABLE_UNITTEST=OFF \
            -DLLVM_ENABLE_BENCHMARKS=OFF \
            -DLLVM_INCLUDE_BENCHMARKS=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DCMAKE_INSTALL_PREFIX=/workspace/llvm-install \
            -DCMAKE_SYSTEM_NAME=Android \
            -DCMAKE_SYSTEM_VERSION=24 \
            -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a
          
          # 5. Build
          cmake --build . -j$(nproc)
          
          # 6. Install
          cmake --install .
        '
        
    - name: Package artifacts
      run: |
        tar -czf llvm-android-arm64.tar.gz llvm-install/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: llvm-android-arm64
        path: llvm-android-arm64.tar.gz
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: llvm-android-arm64.tar.gz
        tag_name: v${{ github.run_number }}
        name: LLVM for Android ARM64 v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
