name: Build Latest Clang for Termux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r27c
        add-to-path: false

    - name: Install Rust and Cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build Clang
      env:
        NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        # 基础设置部分保持不变...
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget pkg-config python3 python3-pip ninja-build cmake || true

        sudo mkdir -p /data
        sudo chmod 777 /data
        
        git clone https://github.com/termux/termux-packages.git
        cd termux-packages
        
        # 创建并配置 termux.properties
        cat > termux.properties << EOF
        TERMUX_APP_PACKAGE=com.termux
        TERMUX_PREFIX=/data/data/com.termux/files/usr
        TERMUX_ANDROID_HOME=${NDK}
        TERMUX_NDK_VERSION=27
        EOF
        
        sudo mkdir -p /data/data/com.termux/files/usr
        sudo chmod -R 777 /data/data
        
        ./scripts/setup-ubuntu.sh || true
        
        # 使用新的包名创建 llvm-18 目录
        mkdir -p packages/llvm-18
        
        # 创建更新后的 LLVM 构建配置
        cat > packages/llvm-18/build.sh << 'EOF'
        TERMUX_PKG_HOMEPAGE=https://clang.llvm.org/
        TERMUX_PKG_DESCRIPTION="LLVM 18 toolchain for Termux"
        TERMUX_PKG_LICENSE="Apache-2.0"
        TERMUX_PKG_MAINTAINER="@termux"
        _PKG_MAJOR_VERSION=18
        TERMUX_PKG_VERSION=${_PKG_MAJOR_VERSION}.1.1
        TERMUX_PKG_REVISION=1
        TERMUX_PKG_SRCURL=https://github.com/llvm/llvm-project/releases/download/llvmorg-${TERMUX_PKG_VERSION}/llvm-project-${TERMUX_PKG_VERSION}.src.tar.xz
        TERMUX_PKG_SHA256=c56be5e9c5f3d3c750d5718332cae127403df852c3685f0ccd765531455e5e04
        TERMUX_PKG_DEPENDS="libc++, ncurses, zlib"
        TERMUX_PKG_BUILD_DEPENDS="binutils-libs, libffi-static, zlib-static"
        TERMUX_PKG_PROVIDES="clang-${_PKG_MAJOR_VERSION}, llvm-${_PKG_MAJOR_VERSION}"
        TERMUX_PKG_CONFLICTS="clang-${_PKG_MAJOR_VERSION}, llvm-${_PKG_MAJOR_VERSION}"
        TERMUX_PKG_REPLACES="clang-${_PKG_MAJOR_VERSION}, llvm-${_PKG_MAJOR_VERSION}"
        TERMUX_PKG_GROUPS="base-devel"

        termux_step_pre_configure() {
          # Build configuration:
          TERMUX_LLVM_BUILD_CONFIGURATION=Release
          
          LLVM_DEFAULT_TARGET_TRIPLE=$TERMUX_HOST_PLATFORM
          LLVM_TARGET_ARCH=$TERMUX_ARCH
          
          # Add flags for LLVM build:
          TERMUX_PKG_EXTRA_CONFIGURE_ARGS+="
            -DLLVM_TARGET_ARCH=$LLVM_TARGET_ARCH
            -DLLVM_TARGETS_TO_BUILD=ARM;AArch64;X86
            -DLLVM_HOST_TRIPLE=$LLVM_DEFAULT_TARGET_TRIPLE
            -DLLVM_BUILD_LLVM_DYLIB=ON
            -DLLVM_LINK_LLVM_DYLIB=ON
            -DCLANG_DEFAULT_LINKER=lld
            -DCLANG_DEFAULT_CXX_STDLIB=libc++
            -DLLVM_ENABLE_PROJECTS=clang;compiler-rt;lld;polly
            -DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind
            -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON
            -DLLVM_ENABLE_ASSERTIONS=OFF
            -DLLVM_ENABLE_FFI=ON
            -DLLVM_ENABLE_TERMINFO=ON
            -DLLVM_ENABLE_THREADS=ON
            -DLLVM_PARALLEL_LINK_JOBS=1
          "
        }
        EOF
        
        # 设置执行权限
        chmod +x packages/llvm-18/build.sh
        
        # 构建新的包
        ./build-package.sh -a arm64 -f llvm-18

    - name: Package artifacts
      run: |
        mkdir -p artifacts
        cp termux-packages/debs/llvm-18*.deb artifacts/ || true
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: llvm-18-clang-termux-arm64
        path: artifacts/*.deb
