name: Build Latest Clang for Termux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Clang
      run: |
        # 克隆 Termux 的包构建仓库
        git clone https://github.com/termux/termux-packages.git
        cd termux-packages
        
        # 手动安装依赖
        sudo apt-get update
        sudo apt-get install -y \
          android-sdk-build-tools \
          asciidoc \
          asciidoctor \
          autoconf \
          automake \
          bison \
          build-essential \
          curl \
          devscripts \
          docbook-to-man \
          docbook-utils \
          ed \
          flex \
          g++-multilib \
          gawk \
          gcc-multilib \
          git \
          gnupg \
          gperf \
          help2man \
          intltool \
          jq \
          libexpat1-dev \
          libffi-dev \
          libgc-dev \
          libgmp-dev \
          libgnustep-base-dev \
          libjpeg-dev \
          libltdl-dev \
          libmpc-dev \
          libmpfr-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libssl-dev \
          libtool-bin \
          libwxgtk3.0-gtk3-dev \
          lzip \
          m4 \
          patchelf \
          pkg-config \
          python3-docutils \
          python3-pip \
          python3-setuptools \
          python3-sphinx \
          ruby \
          scons \
          texinfo \
          unzip \
          xfonts-utils \
          xmlto \
          zip \
          zlib1g-dev

        # 安装 tree-sitter-cli
        cargo install tree-sitter-cli || true
        
        # 设置构建环境
        ./scripts/setup-ubuntu.sh || true
        
        # 修改 LLVM 包配置以使用最新版本
        sed -i 's/TERMUX_PKG_VERSION=.*/TERMUX_PKG_VERSION=18.1.1/' packages/llvm/build.sh
        sed -i 's/TERMUX_PKG_REVISION=.*/TERMUX_PKG_REVISION=1/' packages/llvm/build.sh
        
        # 更新源码下载链接
        sed -i 's|TERMUX_PKG_SRCURL=.*|TERMUX_PKG_SRCURL=https://github.com/llvm/llvm-project/releases/download/llvmorg-${TERMUX_PKG_VERSION}/llvm-project-${TERMUX_PKG_VERSION}.src.tar.xz|' packages/llvm/build.sh
        
        # 构建 LLVM/Clang
        ./build-package.sh -a arm64 -f llvm

    - name: Package artifacts
      run: |
        mkdir -p artifacts
        cp termux-packages/debs/llvm*.deb artifacts/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: llvm-clang-termux-arm64
        path: artifacts/*.deb
